---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader-binding
  namespace: $NAMESPACE
subjects:
- kind: ServiceAccount
  name: default
  namespace: $NAMESPACE
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: $NAMESPACE
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---
apiVersion: v1
kind: Service
metadata:
  name: pods-api-svc
  namespace: $NAMESPACE
  labels:
    name: pods-api
spec:
  type: ClusterIP
  ports:
  - name: server
    port: 5000
  selector:
    name: pods-api


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pods-api
  namespace: $NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pods-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        name: pods-api
    spec:
      containers:
      - name: pods-api
        image: anujpatel800/pods-status:latest
        imagePullPolicy: Always
        env:
        - name: X_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "768Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
          name: server
